version: '3'

networks: 
  app-network:
    driver: bridge    

services:
  app: 
    build: 
      dockerfile: Dockerfile.node.dockerize
    container_name: app
    ports: 
      - "3000:4000"
    volumes:
      - ./node:/app
    tty: true
    working_dir: /app
    entrypoint: dockerize -wait tcp://db:3306 -timeout 20s node index.js
    networks:
      - app-network
    depends_on:
      - db

  server:
    build: 
      dockerfile: Dockerfile.nginx.dockerize
    volumes:
      - ./nginx/configs/:/etc/nginx/conf.d/:ro
    container_name: server
    ports: 
      - "8080:80"
    networks:
      - app-network
    depends_on:
      - db

  db:
    build:
      dockerfile: Dockerfile.mysql
    container_name: db
    tty: true
    volumes: 
      - ./mysql:/var/lib/mysql
    environment: 
      - MYSQL_DATABASE=nodedb
      - MYSQL_USER=root
      - MYSQL_ROOT_HOST=% 
    networks: 
      - app-network


# docker-compose -f ./docker-compose.nginx.yaml up -d --build
# docker exec -it app /bin/bash